### ISSUE TITLE
Test failing on Julia 1.0

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaDiff/ForwardDiff.jl#346] opened 2018-08-12 18:56 UTC
Just wanted to get this out:

(v1.0) pkg> test ForwardDiff
   Testing ForwardDiff
 Resolving package versions...
    Status `/var/folders/j5/12tsmc_s7xs31bmt68r6z0xh4m4bb6/T/tmpcFDwDf/Manifest.toml`
  [9e28174c] BinDeps v0.8.9
  [b99e7846] BinaryProvider v0.4.0
  [49dc2e85] Calculus v0.4.1
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v1.0.1
  [163ba53b] DiffResults v0.0.3
  [b552c78f] DiffRules v0.0.7
  [de460e47] DiffTests v0.1.0
  [f6369f11] ForwardDiff v0.8.4
  [77ba4419] NaNMath v0.3.2
  [276daf66] SpecialFunctions v0.7.0
  [90137ffa] StaticArrays v0.8.3
  [30578b45] URIParser v0.4.0
  [2a0f44e3] Base64  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Base64`]
  [ade2ca70] Dates  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Dates`]
  [8bb1440f] DelimitedFiles  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/DelimitedFiles`]
  [8ba89e20] Distributed  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Distributed`]
  [b77e0a4c] InteractiveUtils  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/InteractiveUtils`]
  [76f85450] LibGit2  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/LibGit2`]
  [8f399da3] Libdl  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Libdl`]
  [37e2e46d] LinearAlgebra  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/LinearAlgebra`]
  [56ddb016] Logging  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Logging`]
  [d6f4376e] Markdown  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Markdown`]
  [a63ad114] Mmap  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Mmap`]
  [44cfe95a] Pkg  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Pkg`]
  [de0858da] Printf  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Printf`]
  [3fa0cd96] REPL  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/REPL`]
  [9a3f8284] Random  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Random`]
  [ea8e919c] SHA  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/SHA`]
  [9e88b42a] Serialization  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Serialization`]
  [1a1011a3] SharedArrays  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/SharedArrays`]
  [6462fe0b] Sockets  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Sockets`]
  [2f01184e] SparseArrays  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/SparseArrays`]
  [10745b16] Statistics  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Statistics`]
  [8dfed614] Test  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Test`]
  [cf7118a7] UUIDs  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/UUIDs`]
  [4ec0a83e] Unicode  [`~/src/julia/usr/bin/../share/julia/stdlib/v1.0/Unicode`]
Testing Partials...
  ...testing Partials{0,Int64}
Error During Test at /Users/arora/.julia/packages/ForwardDiff/2v3a4/test/PartialsTest.jl:39
  Test threw exception
  Expression: start(PARTIALS) == start(VALUES)
  UndefVarError: start not defined
  Stacktrace:
   [1] top-level scope at /Users/arora/.julia/packages/ForwardDiff/2v3a4/test/PartialsTest.jl:39
   [2] include at ./boot.jl:317 [inlined]
   [3] include_relative(::Module, ::String) at ./loading.jl:1038
   [4] include(::Module, ::String) at ./sysimg.jl:29
   [5] include(::String) at ./client.jl:388
   [6] top-level scope at util.jl:213
   [7] include at ./boot.jl:317 [inlined]
   [8] include_relative(::Module, ::String) at ./loading.jl:1038
   [9] include(::Module, ::String) at ./sysimg.jl:29
   [10] include(::String) at ./client.jl:388
   [11] top-level scope at none:0
   [12] eval(::Module, ::Any) at ./boot.jl:319
   [13] macro expansion at ./logging.jl:317 [inlined]
   [14] exec_options(::Base.JLOptions) at ./client.jl:219
   [15] _start() at ./client.jl:421
ERROR: LoadError: LoadError: There was an error during testing
in expression starting at /Users/arora/.julia/packages/ForwardDiff/2v3a4/test/PartialsTest.jl:10
in expression starting at /Users/arora/.julia/packages/ForwardDiff/2v3a4/test/runtests.jl:4
ERROR: Package ForwardDiff errored during testing

**Comment by jrevels** [comment] 2018-08-13 00:54
I believe this was fixed in https://github.com/JuliaDiff/ForwardDiff.jl/commit/14bb015f03aa41b682c1e3735f9e10772e2f6b14. 

Can you update ForwardDiff and try again?

**Comment by kibaekkim** [comment] 2018-08-13 11:50
I confirm that I have the same issue with v1.0.

**Comment by jrevels** [comment] 2018-08-14 16:43
Can't reproduce locally or on CI, so I'm going to close this. Feel free to reopen if you test on the latest release of ForwardDiff and still have the issue.

**Closed by jrevels** 2018-08-14 16:43 UTC
