### ISSUE TITLE
Wrong type for subtypes of StaticVector

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/ForwardDiff.jl#235] opened 2017-05-28 21:14 UTC
```jl
julia> using StaticArrays, IntervalArithmetic, ForwardDiff
INFO: Precompiling module ForwardDiff.

julia> f(X) = ((x,y) = X; SVector(x-y, x+y))
f (generic function with 1 method)

julia> ForwardDiff.jacobian(f, SVector(0..0, 1..1))
2×2 StaticArrays.SArray{Tuple{2,2},IntervalArithmetic.Interval{Float64},2,4}:
 [1, 1]  [-1, -1]
 [1, 1]    [1, 1]

julia> ForwardDiff.jacobian(f, IntervalBox(0..0, 1..1))
2×2 Array{IntervalArithmetic.Interval{Float64},2}:
 [1, 1]  [-1, -1]
 [1, 1]    [1, 1]
```

The last result is no longer an `SArray`, even though `IntervalBox` is a subtype of `StaticVector`.

**Comment by dpsanders** [comment] 2017-05-28 21:14
I would actually like to be able to define
```jl
julia> f(X) = ((x,y) = X; IntervalBox(x-y, x+y))
f (generic function with 1 method)
```
but this gives
```
julia> ForwardDiff.jacobian(f, IntervalBox(0..0, 1..1))
ERROR: No precise constructor for IntervalArithmetic.IntervalBox found. Length of input was 2.
Stacktrace:
 [1] f(::MVector{2,ForwardDiff.Dual{ForwardDiff.Tag{#f,0x0f6d05fba59ad3d6},IntervalArithmetic.Interval{Float64},2}}) at ./REPL[5]:1
 [2] vector_mode_jacobian(::#f, ::IntervalArithmetic.IntervalBox{2,Float64}, ::ForwardDiff.JacobianConfig{ForwardDiff.Tag{#f,0x0f6d05fba59ad3d6},IntervalArithmetic.Interval{Float64},2,MVector{2,ForwardDiff.Dual{ForwardDiff.Tag{#f,0x0f6d05fba59ad3d6},IntervalArithmetic.Interval{Float64},2}}}) at /Users/dpsanders/.julia/v0.6/ForwardDiff/src/jacobian.jl:132
 [3] jacobian at /Users/dpsanders/.julia/v0.6/ForwardDiff/src/jacobian.jl:21 [inlined]
 [4] jacobian(::#f, ::IntervalArithmetic.IntervalBox{2,Float64}) at /Users/dpsanders/.julia/v0.6/ForwardDiff/src/jacobian.jl:20
```
cc @andyferris

**Comment by andyferris** [comment] 2017-05-29 00:30
Is `IntervalBox` missing a constructor along the lines of
```julia
function IntervalBox(t::NTuple{N, <:Interval}) where {N}
    IntervalBox{N}(t)
end
```
?

**Comment by andyferris** [comment] 2017-05-29 00:32
(sorry - because abstract constructors are *really* hard to get right on my end, user-defined types typically have to populate their type parameters themselves).

**Comment by dpsanders** [comment] 2017-05-29 01:22
Thanks, but adding that gives
```
julia> ForwardDiff.jacobian(f, IntervalBox(0..1, 1..2))
ERROR: No precise constructor for IntervalArithmetic.IntervalBox{2,T} where T found. Length of input was 2.
Stacktrace:
 [1] IntervalArithmetic.IntervalBox(::IntervalArithmetic.Interval{Float64}, ::IntervalArithmetic.Interval{Float64}) at /Users/dpsanders/.julia/v0.6/StaticArrays/src/convert.jl:3
```

**Comment by dpsanders** [comment] 2017-05-29 01:59
I can't claim to understand `where` yet, but I also tried
```
function IntervalBox(t::NTuple{N, Interval{T}}) where N where T<:Real
    @show N, T
    @show t
    @show t isa NTuple{N, Interval{T}}
    IntervalBox{N,T}(t)
end
```
This is the constructor that gets called, and gives
julia> ForwardDiff.jacobian(f, IntervalBox(0..1, 1..2))
(N, T) = (2, Float64)
t = ([0, 1], [1, 2])
t isa NTuple{N, Interval{T}} = true
ERROR: No precise constructor for IntervalArithmetic.IntervalBox found. Length of input was 2.
Stacktrace:
 [1] f(::MVector{2,ForwardDiff.Dual{ForwardDiff.Tag{#f,0x0f6d05fba59ad3d6},IntervalArithmetic.Interval{Float64},2}}) at ./REPL[2]:1
 [2] vector_mode_jacobian(::#f, ::IntervalArithmetic.IntervalBox{2,Float64}, ::ForwardDiff.JacobianConfig{ForwardDiff.Tag{#f,0x0f6d05fba59ad3d6},IntervalArithmetic.Interval{Float64},2,MVector{2,ForwardDiff.Dual{ForwardDiff.Tag{#f,0x0f6d05fba59ad3d6},IntervalArithmetic.Interval{Float64},2}}}) at /Users/dpsanders/.julia/v0.6/ForwardDiff/src/jacobian.jl:132
 [3] jacobian at /Users/dpsanders/.julia/v0.6/ForwardDiff/src/jacobian.jl:21 [inlined]
 [4] jacobian(::#f, ::IntervalArithmetic.IntervalBox{2,Float64}) at /Users/dpsanders/.julia/v0.6/ForwardDiff/src/jacobian.jl:20
```
I don't understand this, since it seems to be indeed calling the correct constructor of `Interval{N,T}`.

**Comment by andyferris** [comment] 2017-05-29 04:13
I'm not sure what the problem with `IntervalBox` is. Why is that stack trace talking about `MVector` in `f`?

**Comment by andyferris** [comment] 2017-05-29 04:15
`IntervalBox` is defining a method for `Size` on Julia v0.6 - I'd move that method inside the v0.5 code fence.

https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/src/multidim/intervalbox.jl#L23

That might be unrelated to the problem here though.

**Comment by jrevels** [comment] 2017-05-29 11:43
Tried to reproduce using Julia v0.6.0-rc2.0, but:

```julia
julia> using IntervalArithmetic
INFO: Precompiling module IntervalArithmetic.

WARNING: deprecated syntax "abstract AbstractInterval<:Real" at /Users/jarrettrevels/.julia/v0.6/IntervalArithmetic/src/intervals/intervals.jl:9.
Use "abstract type AbstractInterval<:Real end" instead.

WARNING: deprecated syntax "inner constructor Interval(...) around /Users/jarrettrevels/.julia/v0.6/IntervalArithmetic/src/intervals/intervals.jl:16".
Use "Interval{T}(...) where T" instead.
ERROR: LoadError: LoadError: LoadError: too many parameters for type
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Users/jarrettrevels/.julia/v0.6/IntervalArithmetic/src/multidim/intervalbox.jl, in expression starting on line 8
while loading /Users/jarrettrevels/.julia/v0.6/IntervalArithmetic/src/multidim/multidim.jl, in expression starting on line 1
while loading /Users/jarrettrevels/.julia/v0.6/IntervalArithmetic/src/IntervalArithmetic.jl, in expression starting on line 80
ERROR: Failed to precompile IntervalArithmetic to /Users/jarrettrevels/.julia/lib/v0.6/IntervalArithmetic.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398
```

I got the same message whether I'm using IntervalArithmetic master or the latest tag.

**Comment by jrevels** [comment] 2017-05-29 12:20
Okay, I reproduced the OP. Given the implementation of StaticArrays/IntervalArithmetic, the ForwardDiff behavior given in the OP is correct and expected. Since it's not really a ForwardDiff issue, I'll close this, though feel free to continue discussion here if you'd like.

> Why is that stack trace talking about MVector in f?

Generally, ForwardDiff needs mutable work buffers to store the `Dual`s. These work buffers can be constructed via the [AbstractConfig API](http://www.juliadiff.org/ForwardDiff.jl/stable/user/api.html#Preallocating/Configuring-Work-Buffers-1), which calls `similar` to perform the allocation. For specifics, you can see the default values for the optional arguments listed in that same document.

Recently, I added specialized codepaths for `SArray` that avoids allocating mutable arrays. Note that extending those codepaths to all `A<:StaticArray` would be a bad idea, since performance would likely suffer for mutable `A`. 

Would it be possible for StaticArrays to offer an abstract type `ImmutableArray <: StaticArray` that ForwardDiff could work with instead of `SArray`s directly? Then `IntervalBox <: ImmutableArray` and @dpsanders could get the desired behavior without having to do manual type conversion.

**Closed by jrevels** 2017-05-29 12:20 UTC

**Comment by andyferris** [comment] 2017-05-29 13:13
> Would it be possible for `StaticArrays` to offer an abstract type `ImmutableArray <: StaticArray` that ForwardDiff could work with

I'd prefer a trait - would that suit?

I think I'd even make the trait it's own micro-package (for `Base` types and for packages to extend)

**Comment by dpsanders** [comment] 2017-05-29 13:36
Thanks @jrevels. A trait sounds like a good solution, @andyferris.
