### ISSUE TITLE
NaN return

### ISSUE THREAD

**Issue by genwei007** [JuliaDiff/ForwardDiff.jl#171] opened 2016-12-08 11:00 UTC
Hi ForwardDiff developers,

I got an example that cannot obtain derivative for the probability function at the point `Theta = x[1]`. I suppose it should return 0 but NaN.
~~~
function f(x,Theta,point)
C = point-1
dim = length(Theta)
q = ones(eltype(x),C)
p = ones(eltype(x),C)
prob = ones(eltype(x),1,point)
TD = sqrt( ((Theta-x[1])*x[1+C+1:1+C+dim]).^2 )
for k = 1:C
    td = cosh((0.5*(2*C+1)+1-k)*TD)./cosh((0.5*(2*C+1)-k)*TD)
    rho = cosh((0.5*(2*C+1)+1-k)*x[1+k])./cosh((0.5*(2*C+1)-k)*x[1+k])
    de = td+rho
    tdde = td./de
    q[k] = tdde[1]
    rhode = rho./de
    p[k] = rhode[1]
end
prob[1] = prod(q)
for k = 2:(point-1)
    prob[k] = prod(p[1:(k-1)])*prod(q[k:C])
end
prob[point] = prod(p)
de = sum(prob)
for k = 1:point
    prob[k] = prob[k]./de
end
return prob
end
using ForwardDiff
x = [0.,3.,2.,1. ,1.]
point = 4
cfg = ForwardDiff.JacobianConfig(x)
g = (x,t,c) -> ForwardDiff.jacobian(x -> f(x,t,c), x, cfg)
g(x,0,4)
~~~

**Comment by jrevels** [comment] 2016-12-08 16:16
This is happening because of `sqrt(((Theta-x[1])*x[1+C+1:1+C+dim]).^2 )`. Reducing that line using the given input values, we can minimally reproduce the problem as:

```julia
julia> ForwardDiff.derivative(x -> sqrt(x^2), 0.0)
NaN
```

Note that [this is an appropriate interpretation of this derivative](https://www.wolframalpha.com/input/?i=derivative+of+sqrt(x%5E2)+at+x%3D0) - in other words, ForwardDiff is giving you a "correct" answer at the input you gave.

See [here](http://stackoverflow.com/a/40811656/7007793) for an explanation of the rationale behind `NaN` propagation in forward-mode AD.

This kind of issue arises pretty frequently...we should have better documentation for it.

**Comment by genwei007** [comment] 2016-12-08 16:46
Thanks for the answer! BTW, I have an another question about the line 'g = (x,t,c) -> ForwardDiff.jacobian(x -> f(x,t,c), x, cfg)'. Is it the most efficient way (run fastest in Julia) for ForwardDiff? I learned this line from other discussion, but not the document here.

**Comment by jrevels** [comment] 2016-12-08 17:54
Close! It should be even faster if you preallocate an output buffer that you can reuse for subsequent calls. For example:

```julia
Jf!(out, x, t, c) = ForwardDiff.jacobian!(out, x -> f(x, t, c), x, cfg)
```

where `out` is some preallocated array in which the Jacobian matrix will be stored. 

This can be further improved if `f` itself can reuse preallocated arrays. Then, you'd have something like `f!(prob, x, Theta, point)` where `f!` loads values into `prob` instead of allocating `prob` internally for every call. Then you could do:

```julia
Jf!(out, prob, x, t, c) = ForwardDiff.jacobian!(out, (prob, x) -> f!(prob, x, t, c), prob, x, cfg)
```

**Comment by KristofferC** [comment] 2016-12-08 17:59
Note that your function itself has some (arguably unnecessary) allocations so preallocating an output buffer for ForwardDiff will have little net benefit. The part I am looking at is

```jl
 prod(p[1:(k-1)])*prod(q[k:C])
```

which will allocate two arrays for each loop iteration.

**Comment by jrevels** [comment] 2016-12-08 19:18
Feel free to keep discussing the code here, but I'm going to close this since there doesn't seem to be an action item for ForwardDiff.

**Closed by jrevels** 2016-12-08 19:18 UTC
